### ISSUE TITLE
Error when trying to swap ustc for lunc using ledger via terra station mobile app

### ISSUE THREAD

**Issue by Vagab0ndJ0hn** [classic-terra/station#4]
![Screenshot_20230721_091436_Station.jpg](https://github.com/classic-terra/station/assets/141286620/8930950e-1685-4090-bf48-fafc2454a0ba)

**Comment by ventluc** [comment]
I have the same problem!

**Comment by echel0n-HX** [comment]
Hi, sorry but we do not support TFL Terra Station mobile, only Terra Classic Station
